function manifest = manifest_schema(request, execution_plan)
%MANIFEST_SCHEMA Create an in-memory AAA manifest with stable field names.

if nargin < 1 || isempty(request)
    request = aaa.schema.default_request("dual", "single");
end
if nargin < 2 || isempty(execution_plan)
    [~,~,~,execution_plan] = aaa.schema.resolve_sections( ...
        request.mode, request.workflow.preset, request.workflow.sections);
end

names = fieldnames(execution_plan);
section_status = struct();
for idx = 1:numel(names)
    name = names{idx};
    section_status.(name) = struct( ...
        'action', string(execution_plan.(name)), ...
        'state', "pending", ...
        'started_at', NaT, ...
        'completed_at', NaT, ...
        'message', "");
end

source = aaa.io.source_provenance();

manifest = struct( ...
    'manifest_schema_version', "2.0.0", ...
    'results_schema', "AAA.results.v1", ...
    'app_name', "AP_Analysis_APP", ...
    'app_short_name', "AAA", ...
    'analysis_type', string(request.mode), ...
    'scope', string(request.scope), ...
    'status', "pending", ...
    'request', request, ...
    'resolved_execution_plan', execution_plan, ...
    'section_status', section_status, ...
    'completed_sections', strings(0,1), ...
    'failed_section', "", ...
    'input_path', string(request.input_path), ...
    'input_sources', repmat(empty_input_source(),0,1), ...
    'output_path', string(request.workflow.output_path), ...
    'source_results_path', string(request.workflow.source_results_path), ...
    'roi_path', string(request.workflow.roi_path), ...
    'results', repmat(empty_result_record(),0,1), ...
    'compatibility_history', repmat(empty_compatibility_report(),0,1), ...
    'output_files', strings(0,1), ...
    'log_file', "", ...
    'manifest_file', "", ...
    'started_at', datetime('now'), ...
    'completed_at', NaT, ...
    'error', empty_error(), ...
    'source', source);
end

function value = empty_result_record()
value = struct('section',"",'file',"",'relative_file',"", ...
    'schema',"",'roles',strings(0,1),'status',"",'saved_at',NaT, ...
    'source_results',strings(0,1));
end

function value = empty_compatibility_report()
value = struct('source_path',"",'absolute_source_path',"", ...
    'detected_schema',"",'adapter_used',"", ...
    'source_files',strings(0,1),'absolute_source_files',strings(0,1), ...
    'relative_source_files',strings(0,1),'frame_rate_source',struct(), ...
    'mapped_fields',strings(0,1),'missing_fields',strings(0,1), ...
    'warnings',strings(0,1),'loaded_at',NaT);
end

function value=empty_input_source()
value=struct('role',"",'camera_index',NaN,'logical_path',"", ...
    'resolved_path',"",'physical_files',strings(0,1), ...
    'is_split',false,'part_count',0,'resolution_method',"", ...
    'frame_rate',NaN,'frame_count',0,'reuse_source_path',"", ...
    'reuse_result_file',"", ...
    'movie_loaded',false);
end

function value = empty_error()
value = struct('identifier',"",'message',"",'stack',struct([]));
end
