function catalog = parameter_catalog(mode, scope)
%PARAMETER_CATALOG Return public AAA parameters and App-control metadata.
% Every entry is intentionally UI-addressable. Boolean defaults and legacy
% fallback decisions use checkbox controls instead of remaining hidden in
% workflow code.

catalog = repmat(empty_entry(), 0, 1);

% Common request and output controls.
catalog = add(catalog, 'input_path','all','all','input','Paths','Basic','path','Input path', ...
    'Input movie/Cycle path for single scope or Record path for record scope.','path',"",'',[],[],[],"",'AAA request');
catalog = add(catalog, 'workflow.output_path','all','all','export','Paths','Basic','path','Output folder', ...
    'Optional explicit output folder. Empty lets the workflow use its legacy naming rule.','path',"",'',[],[],[],"",'legacy save_path');
catalog = add(catalog, 'workflow.run_name','all','all','export','Paths','Advanced','edit','Run name', ...
    'Optional run-folder name. Empty uses the workflow timestamp rule.','string',"",'',[],[],[],"",'legacy analysis_run_name');
catalog = add(catalog, 'workflow.source_results_path','all','all','input','Reuse','Basic','path','Source results', ...
    'Read-only result folder or Cycle/Record search root used by reuse actions.','path',"",'',[],[],[],"",'legacy reuse_results_path');
catalog = add(catalog, 'workflow.auto_detect_reuse_source','all','all','input','Reuse','Basic','checkbox','Auto-detect reuse source', ...
    'When reuse is requested, resolve each Cycle to the newest complete compatible result if Source results is blank or is a search root.','logical',true,'',[],[],[],"",'AAA reuse resolver');
catalog = add(catalog, 'workflow.discovery_max_depth','all','all','input','Reuse','Advanced','numeric','Reuse scan depth', ...
    'Maximum directory depth searched below each Cycle. A truncated scan never auto-selects a result.','integer',4,'levels',[],1,12,"",'AAA bounded discovery');
catalog = add(catalog, 'workflow.discovery_max_mat_files','all','all','input','Reuse','Advanced','numeric','Reuse MAT limit', ...
    'Maximum candidate result MAT anchors inspected per Cycle before manual source is required.','integer',500,'files',[],10,5000,"",'AAA bounded discovery');
catalog = add(catalog, 'workflow.roi_path','all','all','roi','Reuse','Basic','path','ROI source', ...
    'Optional ROI-specific source folder or file.','path',"",'',[],[],[],"",'legacy roi_path/reuse_roi_file');
catalog = add(catalog, 'workflow.write_analysis_log','all','all','export','Logging','Basic','checkbox','Write analysis log', ...
    'Required AAA traceability log written in the result folder.','logical',true,'',[],[],[],"",'AAA traceability requirement');
catalog(end).editable = false;
catalog(end).default_rule = "required=true for every validated workflow";
catalog = add(catalog, 'workflow.write_manifest','all','all','export','Logging','Basic','checkbox','Write manifest', ...
    'Write analysis_manifest.mat as the App/result index.','logical',true,'',[],[],[],"",'approved AAA manifest');
catalog = add(catalog, 'workflow.save_code_snapshot','all','all','export','Logging','Advanced','checkbox','Save code snapshot', ...
    'Disabled in AAA. The manifest records App/Git/MATLAB/dependency versions and a production-source SHA-256 digest instead.','logical',false,'',[],[],[],"",'AAA manifest source provenance');
catalog(end).ui_control = "readonly";
catalog(end).editable = false;
catalog(end).default_rule = "disabled; analysis_manifest.mat is the authoritative source record";

catalog = add(catalog, 'workflow.preset','ap','all','input','Workflow','Basic','dropdown','Preset', ...
    'Base AP section plan before table overrides.','enum',"full",'', ...
    ["full","reuse_motion","reuse_trace","skip_motion","analysis_only","motion_only","custom"],[],[],"",'Dual-style AP workflow');
catalog = add(catalog, 'workflow.preset','dual','all','input','Workflow','Basic','dropdown','Preset', ...
    'Base Dual section plan before table overrides.','enum',"full",'', ...
    ["full","reuse_motion","reuse_trace","skip_motion","analysis_only","motion_only","custom"],[],[],"",'resolve_dual3_sections');
catalog = add(catalog, 'workflow.offset_mode','dual','all','registration','Registration','Basic','dropdown','Registration mode', ...
    'Inter-camera offset method.','enum',"manual_points",'', ...
    ["none","manual_points","matlab_register"],[],[],"",'legacy correct_offset_mode');
catalog = add(catalog, 'workflow.reuse_offset','dual','all','registration','Registration','Advanced','table','Reuse offset', ...
    'Saved [x y] offset using voltage_position = calcium_position + offset.','numeric_vector',[], 'pixels',[],[],[],"workflow.offset_mode == 'none'",'legacy reuse_offset');

% Common processing and motion controls.
catalog = add(catalog, 'params.common.gpu','all','all','input','Runtime','Basic','checkbox','Use parallel/GPU path', ...
    'Request the legacy accelerated path; the backend may fall back and logs the outcome.','logical',true,'',[],[],[],"",'legacy gpu');
catalog = add(catalog, 'params.common.run_background_removal','all','all','trace','Trace','Basic','checkbox','Background removal', ...
    'Run ROI background fitting/removal before bleach correction.','logical',true,'',[],[],[],"",'legacy run_background_removal');
catalog = add(catalog, 'params.common.background.inner_distance','all','all','trace','Background','Advanced','numeric','Background inner distance', ...
    'Inner ROI dilation radius excluded from the background annulus.','integer',2,'pixels',[],0,Inf,"",'Dual remove_background default inner_distance=2');
catalog = add(catalog, 'params.common.background.outer_distance','all','all','trace','Background','Advanced','numeric','Background outer distance', ...
    'Outer ROI dilation radius defining the background annulus.','integer',32,'pixels',[],1,Inf,"",'Dual remove_background default outer_distance=32');
catalog = add(catalog, 'params.common.background.background_fraction','all','all','trace','Background','Advanced','numeric','Low-intensity fraction', ...
    'Fraction of lowest mean-intensity annulus pixels retained as background.','double',0.05,'fraction',[],eps,1,"",'Dual remove_background default 0.05');
catalog = add(catalog, 'params.common.background.fit_span','all','all','trace','Background','Expert','numeric','Background fit span', ...
    'Span passed to smooth for the fitted background trace.','double',0.01,'fraction',[],eps,1,"",'Dual remove_background smooth span 0.01');
catalog = add(catalog, 'params.common.background.fit_method','all','all','trace','Background','Expert','dropdown','Background fit method', ...
    'Method passed to smooth for the fitted background trace.','enum',"rloess",'', ...
    ["moving","lowess","loess","sgolay","rlowess","rloess"],[],[],"",'Dual remove_background fit method rloess');
catalog = add(catalog, 'params.common.motion.use_saved_shift','all','all','motion','Motion','Advanced','checkbox','Use saved shifts', ...
    'Apply an explicitly selected saved shift file instead of estimating shifts.','logical',false,'',[],[],[],"",'legacy motion_cfg.use_saved_shift');
catalog = add(catalog, 'params.common.motion.saved_shift_file','all','all','motion','Motion','Advanced','path','Saved voltage shift file', ...
    'Rigid/shared shift file used when Use saved shifts is selected.','path',"",'',[],[],[],"params.common.motion.use_saved_shift",'legacy motion_cfg.saved_shift_file');
catalog = add(catalog, 'params.common.motion.highpass','all','all','motion','Motion','Advanced','checkbox','High-pass for shift estimation', ...
    'Use the high-pass temporary movie for shift estimation.','logical',true,'',[],[],[],"",'legacy motion_cfg.highpass');
catalog = add(catalog, 'params.common.motion.plot_metrics','ap','all','motion','Motion','Advanced','checkbox','Plot motion metrics', ...
    'Generate motion-correction metric outputs.','logical',true,'',[],[],[],"",'legacy AP motion_cfg.plot_metrics / Dual metric output');
catalog = add(catalog, 'params.common.motion.plot_metrics','dual','all','motion','Motion','Advanced','readonly','Plot motion metrics', ...
    'The frozen Dual bridge currently always generates the legacy motion metrics.','logical',true,'',[],[],[],"",'Dual motion metric output fixed during compatibility migration');
catalog(end).editable = false;
catalog(end).default_rule = "always on in frozen Dual motion section";
catalog = add(catalog, 'params.common.motion.save_downsampled_tif','ap','all','motion','Motion','Advanced','checkbox','Save motion QC TIFF', ...
    'Save the temporally downsampled corrected TIFF.','logical',true,'',[],[],[],"",'legacy motion_cfg.save_downsampled_tif');
catalog = add(catalog, 'params.common.motion.save_downsampled_tif','dual','all','motion','Motion','Advanced','readonly','Save motion QC TIFF', ...
    'The frozen Dual bridge currently always writes the legacy motion QC TIFF.','logical',true,'',[],[],[],"",'Dual motion QC TIFF fixed during compatibility migration');
catalog(end).editable = false;
catalog(end).default_rule = "always on in frozen Dual motion section";
catalog = add(catalog, 'params.common.motion.bin_width','all','all','motion','Motion','Expert','numeric','NoRMCorre bin width', ...
    'NoRMCorre rigid batch width.','integer',200,'frames',[],1,Inf,"",'legacy NoRMCorre bin_width=200');
catalog = add(catalog, 'params.common.motion.upsample_factor','all','all','motion','Motion','Expert','numeric','NoRMCorre upsample factor', ...
    'NoRMCorre us_fac.','integer',30,'',[],1,Inf,"",'legacy NoRMCorre us_fac=30');
catalog = add(catalog, 'params.common.motion.iterations','all','all','motion','Motion','Expert','numeric','NoRMCorre iterations', ...
    'NoRMCorre iteration count.','integer',1,'',[],1,Inf,"",'legacy NoRMCorre iter=1');
catalog = add(catalog, 'params.common.motion.correct_bidir','all','all','motion','Motion','Expert','checkbox','Correct bidirectional offset', ...
    'Pass correct_bidir to NoRMCorre.','logical',false,'',[],[],[],"",'legacy NoRMCorre correct_bidir=false');
catalog = add(catalog, 'params.common.motion.downsample_factor','all','all','motion','Motion','Expert','numeric','Motion QC downsample', ...
    'Temporal mean-downsample factor for QC TIFF and metrics.','integer',40,'frames',[],1,Inf,"",'legacy tsub/downsample_factor=40');
catalog = add(catalog, 'params.common.motion.display_quantile_low','all','all','motion','Motion','Expert','numeric','Motion TIFF low quantile', ...
    'Lower intensity quantile used for motion QC TIFF scaling.','double',0.0005,'fraction',[],0,1,"",'legacy quantile 0.0005');
catalog = add(catalog, 'params.common.motion.display_quantile_high','all','all','motion','Motion','Expert','numeric','Motion TIFF high quantile', ...
    'Upper intensity quantile used for motion QC TIFF scaling.','double',0.99995,'fraction',[],0,1,"",'legacy quantile 0.99995');

% AP single-channel parameters (names intentionally mirror legacy variables).
catalog = add(catalog, 'params.ap.freq','ap','all','input','Voltage channel','Basic','numeric','Frame rate', ...
    'Single-channel voltage sampling rate.','double',400,'Hz',[],eps,Inf,"",'legacy freq');
catalog = add(catalog, 'params.ap.camera_index','ap','all','input','Voltage channel','Advanced','numeric','Camera index', ...
    'Camera number used to resolve the matching visual-stim sync column.','integer',1,'',[],1,Inf,"",'new public visual-stim camera assignment');
catalog = add(catalog, 'params.ap.transpose_before_analysis','ap','all','input','Voltage channel','Basic','checkbox','Transpose movie', ...
    'Transpose every frame before analysis.','logical',false,'',[],[],[],"",'legacy transpose_before_analysis');
catalog = add(catalog, 'params.ap.bin','ap','all','roi','ROI','Advanced','numeric','Map bin', ...
    'Legacy AP map/bin parameter.','integer',1,'frames',[],1,Inf,"",'legacy bin');
catalog = add(catalog, 'params.ap.bleachmode','ap','all','trace','Trace','Basic','dropdown','Bleach removal', ...
    'AP bleach-removal method.','enum',"linear",'',["linear","highpass","exp2"],[],[],"",'legacy bleachmode');
catalog = add(catalog, 'params.ap.Dnmethods','ap','all','trace','Denoising','Advanced','edit','Denoising method', ...
    'wdenoise DenoisingMethod.','string',"FDR",'',[],[],[],"",'legacy Dnmethods');
catalog = add(catalog, 'params.ap.Dnlevel','ap','all','trace','Denoising','Advanced','numeric','Denoising level', ...
    'wdenoise decomposition level.','integer',8,'',[],1,Inf,"",'legacy Dnlevel');
catalog = add(catalog, 'params.ap.Wavename','ap','all','trace','Denoising','Advanced','edit','Wavelet name', ...
    'wdenoise wavelet name.','string',"bior6.8",'',[],[],[],"",'legacy Wavename');
catalog = add(catalog, 'params.ap.motion.rigid_max_shift','ap','all','motion','Motion','Expert','numeric','Rigid max shift', ...
    'AP rigid NoRMCorre max_shift.','integer',50,'pixels',[],0,Inf,"",'legacy AP options_r max_shift=50');
catalog = add(catalog, 'params.ap.motion.init_batch','ap','all','motion','Motion','Expert','numeric','Initial motion batch', ...
    'Initial AP motion batch size.','integer',100,'frames',[],1,Inf,"",'legacy init_batch=100');
catalog = add(catalog, 'params.ap.peak_polarity_mode','ap','all','peak','Peaks','Basic','dropdown','Peak polarity', ...
    'AP sensitivity peak polarity rule.','enum',"auto",'',["auto","positive","negative"],[],[],"",'legacy peak_polarity_mode');
catalog = add(catalog, 'params.ap.peak_min_prominence','ap','all','peak','Peaks','Basic','numeric','Minimum prominence', ...
    'AP peak minimum prominence or relative factor.','double',0.3,'',[],0,Inf,"",'legacy peak_min_prominence');
catalog = add(catalog, 'params.ap.peak_min_prominence_mode','ap','all','peak','Peaks','Advanced','dropdown','Prominence mode', ...
    'Interpret prominence as a relative factor or absolute value.','enum',"relative_factor",'',["relative_factor","absolute"],[],[],"",'legacy peak_min_prominence_mode');
catalog = add(catalog, 'params.ap.peak_min_distance_frames','ap','all','peak','Peaks','Basic','numeric','Minimum peak distance', ...
    'Optional override. Empty preserves the legacy rule max(2, round(0.003*freq)).','integer',[],'frames',[],1,Inf,"",'legacy dynamic default');
catalog = add(catalog, 'params.ap.peak_min_height','ap','all','peak','Peaks','Advanced','numeric','Minimum peak height', ...
    'AP peak minimum height.','double',0,'',[],-Inf,Inf,"",'legacy peak_min_height');
catalog = add(catalog, 'params.ap.run_manual_peak_refinement','ap','all','peak','Interaction','Basic','checkbox','Manual voltage peak edit', ...
    'Open the same manual add/delete voltage peak editor used by Dual.','logical',true,'',[],[],[],"",'legacy key retained; behavior unified with Dual');
catalog = add(catalog, 'params.ap.show_roi_saved_dialog','ap','all','roi','Interaction','Advanced','checkbox','Show ROI saved dialog', ...
    'Show the legacy ROI-saved confirmation dialog.','logical',true,'',[],[],[],"",'legacy conditional default for classic');
catalog = add(catalog, 'params.ap.save_failed_peak_debug','ap','all','peak','Diagnostics','Advanced','checkbox','Save failed-peak debug', ...
    'Save diagnostic output when peak processing fails.','logical',false,'',[],[],[],"",'legacy save_failed_peak_debug');
catalog = add(catalog, 'params.ap.enable_peak_redirection','ap','all','ap_events','AP events','Expert','checkbox','Enable peak redirection', ...
    'Permit peak redirection during event construction. The current AP3 effective behavior is disabled.','logical',false,'',[],[],[],"",'effective legacy value forced false before AP events');
catalog = add(catalog, 'params.ap.AP_window_width','ap','all','ap_events','AP events','Basic','numeric','AP half-window', ...
    'Frames retained on each side of each accepted peak.','integer',15,'frames',[],0,Inf,"",'legacy AP_window_width');
catalog = add(catalog, 'params.ap.stim.flash_baseline_window_s','ap','all','stim','Stimulus','Advanced','numeric','Flash baseline window', ...
    'Flash baseline comparison-window duration.','double',2,'s',[],0,Inf,"",'shared Dual visual-stim default');
catalog = add(catalog, 'params.ap.stim.flash_response_window_s','ap','all','stim','Stimulus','Advanced','numeric','Flash response window', ...
    'Flash response comparison-window duration.','double',2,'s',[],0,Inf,"",'shared Dual visual-stim default');
catalog = add(catalog, 'params.ap.stim.voltage_response_method','ap','all','stim','Stimulus','Basic','dropdown','Voltage response', ...
    'Auto uses accepted peak count when available, otherwise mean sensitivity.','enum',"auto",'',["auto","peak_count","mean_sensitivity"],[],[],"",'new public stimulus response choice');
catalog = add(catalog, 'params.ap.stim_context_override','ap','all','stim','Overrides','Expert','table','Stimulus context override', ...
    'Optional expert struct overriding resolved stimulus metadata.','struct',struct(),'',[],[],[],"",'shared visual-stim override');
catalog = add(catalog, 'params.ap.visualization.stim_shading_alpha','ap','all','visualization','Visualization','Expert','numeric','Stimulus shading alpha', ...
    'Transparency of stimulus-window shading.','double',0.14,'fraction',[],0,1,"",'shared Dual visual-stim display default');

% AP statistics and ISI phenotype parameters.
catalog = add_isi_parameters(catalog);

% Dual parameters (legacy names retained beneath params.dual).
catalog = add(catalog, 'params.dual.voltage_frame_rate','dual','all','input','Voltage channel','Basic','numeric','Voltage frame rate', ...
    'Voltage camera analysis frame rate.','double',400,'Hz',[],eps,Inf,"",'legacy voltage_frame_rate');
catalog = add(catalog, 'params.dual.calcium_frame_rate','dual','all','input','Calcium channel','Basic','numeric','Calcium frame rate', ...
    'Calcium camera analysis frame rate.','double',400,'Hz',[],eps,Inf,"",'legacy calcium_frame_rate');
catalog = add(catalog, 'params.dual.voltage_transpose_movie','dual','all','input','Voltage channel','Basic','checkbox','Transpose voltage movie', ...
    'Transpose voltage frames before analysis.','logical',false,'',[],[],[],"",'legacy voltage_transpose_movie');
catalog = add(catalog, 'params.dual.calcium_transpose_movie','dual','all','input','Calcium channel','Basic','checkbox','Transpose calcium movie', ...
    'Transpose calcium frames before analysis.','logical',true,'',[],[],[],"",'legacy calcium_transpose_movie');
catalog = add(catalog, 'params.dual.camera1_role','dual','all','input','Camera assignment','Advanced','dropdown','Camera 1 role', ...
    'Role assigned to rebuilt camera index 1.','enum',"calcium",'',["voltage","calcium"],[],[],"",'legacy camera_cfg(1).role');
catalog = add(catalog, 'params.dual.camera2_role','dual','all','input','Camera assignment','Advanced','dropdown','Camera 2 role', ...
    'Role assigned to rebuilt camera index 2.','enum',"voltage",'',["voltage","calcium"],[],[],"",'legacy camera_cfg(2).role');
catalog = add(catalog, 'params.dual.raw_dual_green_suffix','dual','all','input','Raw-pair compatibility','Expert','edit','Green-folder suffix', ...
    'Suffix used to pair raw two-folder inputs.','string',"_Green",'',[],[],[],"",'legacy raw_dual_green_suffix');
catalog = add(catalog, 'params.dual.raw_dual_primary_role','dual','all','input','Raw-pair compatibility','Expert','dropdown','Primary-folder role', ...
    'Channel role assigned to the primary raw folder.','enum',"voltage",'',["voltage","calcium"],[],[],"",'legacy raw_dual_primary_role');
catalog = add(catalog, 'params.dual.raw_dual_green_role','dual','all','input','Raw-pair compatibility','Expert','dropdown','Green-folder role', ...
    'Channel role assigned to the suffixed raw folder.','enum',"calcium",'',["voltage","calcium"],[],[],"",'legacy raw_dual_green_role');
catalog = add(catalog, 'params.dual.map_bin','dual','all','roi','ROI','Advanced','numeric','Map bin', ...
    'Dual map temporal bin.','integer',4,'frames',[],1,Inf,"",'legacy map_bin');
catalog = add(catalog, 'params.dual.calcium_smoothing_window','dual','all','trace','Calcium channel','Basic','numeric','Calcium smoothing window', ...
    'Final movmean window for calcium raw/sensitivity/SNR traces.','integer',40,'frames',[],1,Inf,"",'legacy calcium_smoothing_window');
catalog = add(catalog, 'params.dual.bleach_mode_voltage','dual','all','trace','Voltage channel','Basic','dropdown','Voltage bleach removal', ...
    'Voltage bleach-removal method.','enum',"linear",'',["linear","highpass","exp2"],[],[],"",'legacy bleach_mode_voltage');
catalog = add(catalog, 'params.dual.bleach_mode_calcium','dual','all','trace','Calcium channel','Basic','dropdown','Calcium bleach removal', ...
    'Calcium bleach-removal method.','enum',"exp2",'',["linear","highpass","exp2"],[],[],"",'legacy bleach_mode_calcium');
catalog = add(catalog, 'params.dual.voltage_polarity','dual','all','trace','Voltage channel','Basic','dropdown','Voltage polarity', ...
    'Display/analysis polarity for voltage traces.','enum',-1,'',[-1 1],[],[],"",'legacy voltage_polarity');
catalog = add(catalog, 'params.dual.calcium_polarity','dual','all','trace','Calcium channel','Basic','dropdown','Calcium polarity', ...
    'Display/analysis polarity for calcium traces.','enum',1,'',[-1 1],[],[],"",'legacy calcium_polarity');
catalog = add(catalog, 'params.dual.voltage_peak_polarity_mode','dual','all','peak','Peaks','Basic','dropdown','Voltage peak polarity mode', ...
    'Global, automatic, positive, or negative voltage peak direction.','enum',"global",'',["global","auto","positive","negative"],[],[],"",'legacy voltage_peak_polarity_mode');
catalog = add(catalog, 'params.dual.voltage_peak_roi_polarity','dual','all','peak','Peaks','Expert','table','Per-ROI peak polarity', ...
    'Optional per-ROI polarity overrides; empty uses the global rule.','numeric_vector',[],'',[],[],[],"",'legacy voltage_peak_roi_polarity');
catalog = add(catalog, 'params.dual.voltage_peak_min_prominence','dual','all','peak','Peaks','Basic','numeric','Voltage minimum prominence', ...
    'Voltage peak minimum prominence or relative factor.','double',0.5,'',[],0,Inf,"",'legacy voltage_peak_min_prominence');
catalog = add(catalog, 'params.dual.voltage_peak_min_prominence_mode','dual','all','peak','Peaks','Advanced','dropdown','Voltage prominence mode', ...
    'Interpret voltage prominence as a relative factor or absolute value.','enum',"relative_factor",'',["relative_factor","absolute"],[],[],"",'legacy voltage_peak_min_prominence_mode');
catalog = add(catalog, 'params.dual.voltage_peak_min_distance_frames','dual','all','peak','Peaks','Basic','numeric','Voltage minimum peak distance', ...
    'Optional override. Empty preserves max(2, round(0.01*voltage_frame_rate)).','integer',[],'frames',[],1,Inf,"",'legacy dynamic default');
catalog = add(catalog, 'params.dual.voltage_peak_min_height','dual','all','peak','Peaks','Advanced','numeric','Voltage minimum peak height', ...
    'Voltage peak minimum height.','double',0,'',[],-Inf,Inf,"",'legacy voltage_peak_min_height');
catalog = add(catalog, 'params.dual.run_manual_voltage_peak_edit','dual','all','peak','Interaction','Basic','checkbox','Manual voltage peak edit', ...
    'Open manual add/delete voltage peak editing.','logical',true,'',[],[],[],"",'legacy run_manual_voltage_peak_edit');
catalog = add(catalog, 'params.dual.motion.saved_calcium_shift_file','dual','all','motion','Motion','Advanced','path','Saved calcium shift file', ...
    'Optional independent calcium shift file.','path',"",'',[],[],[],"params.common.motion.use_saved_shift",'legacy motion_cfg.saved_calcium_shift_file');
catalog = add(catalog, 'params.dual.motion.auto_reuse_previous_shift','dual','all','motion','Motion','Advanced','checkbox','Auto-reuse previous shifts', ...
    'Search for and reuse the latest compatible previous shift file.','logical',false,'',[],[],[],"",'legacy motion_cfg.auto_reuse_previous_shift');
catalog = add(catalog, 'params.dual.motion.max_shift','dual','all','motion','Motion','Expert','numeric','Dual max shift', ...
    'Dual rigid NoRMCorre max_shift.','integer',30,'pixels',[],0,Inf,"",'legacy Dual options_r max_shift=30');
catalog = add(catalog, 'params.dual.noise.voltage_wavelet_level','dual','all','trace','Noise metrics','Expert','numeric','Voltage noise wavelet level', ...
    'Wavelet denoising level used as voltage noise reference.','integer',8,'',[],1,Inf,"",'legacy compute_voltage_metrics level=8');
catalog = add(catalog, 'params.dual.noise.voltage_wavelet_method','dual','all','trace','Noise metrics','Expert','edit','Voltage noise denoising method', ...
    'wdenoise method used as voltage noise reference.','string',"FDR",'',[],[],[],"",'legacy compute_voltage_metrics FDR');
catalog = add(catalog, 'params.dual.noise.voltage_wavelet_name','dual','all','trace','Noise metrics','Expert','edit','Voltage noise wavelet', ...
    'Wavelet used as voltage noise reference.','string',"bior6.8",'',[],[],[],"",'legacy compute_voltage_metrics bior6.8');
catalog = add(catalog, 'params.dual.noise.calcium_filter_order','dual','all','trace','Noise metrics','Expert','numeric','Calcium noise filter order', ...
    'Butterworth order for calcium noise reference.','integer',2,'',[],1,Inf,"",'legacy compute_calcium_metrics order=2');
catalog = add(catalog, 'params.dual.noise.calcium_cutoff_hz','dual','all','trace','Noise metrics','Expert','numeric','Calcium noise cutoff', ...
    'Effective target cutoff for common frame rates.','double',10,'Hz',[],0,Inf,"",'legacy normalized cutoff 20/freq -> 10 Hz');
catalog = add(catalog, 'params.dual.stim.flash_baseline_window_s','dual','all','stim','Stimulus','Advanced','numeric','Flash baseline window', ...
    'Flash baseline comparison-window duration.','double',2,'s',[],0,Inf,"",'legacy flash baseline_window_sec=2');
catalog = add(catalog, 'params.dual.stim.flash_response_window_s','dual','all','stim','Stimulus','Advanced','numeric','Flash response window', ...
    'Flash response comparison-window duration.','double',2,'s',[],0,Inf,"",'legacy flash response_window_sec=2');
catalog = add(catalog, 'params.dual.stim.voltage_response_method','dual','all','stim','Stimulus','Basic','dropdown','Voltage response', ...
    'Auto uses accepted peak count when available, otherwise mean sensitivity.','enum',"auto",'',["auto","peak_count","mean_sensitivity"],[],[],"",'new public stimulus response choice');
catalog = add(catalog, 'params.dual.visualization.stim_shading_alpha','dual','all','visualization','Visualization','Expert','numeric','Stimulus shading alpha', ...
    'Transparency of stimulus-window shading.','double',0.14,'fraction',[],0,1,"",'legacy add_stim_shading alpha=0.14');
catalog = add(catalog, 'params.dual.frequency.min_freq_hz','dual','all','frequency','Frequency','Advanced','numeric','Minimum frequency', ...
    'Lower bound for FFT peak and wavelet display.','double',0.5,'Hz',[],0,Inf,"",'legacy min_freq_hz=0.5');
catalog = add(catalog, 'params.dual.frequency.max_freq_hz','dual','all','frequency','Frequency','Advanced','numeric','Maximum frequency', ...
    'Requested upper bound, capped at channel Nyquist frequencies.','double',80,'Hz',[],0,Inf,"",'legacy min(80, Nyquist)');
catalog = add(catalog, 'params.dual.frequency.wavelet_voices_per_octave','dual','all','frequency','Frequency','Expert','numeric','Wavelet voices per octave', ...
    'Requested CWT voices-per-octave metadata.','integer',12,'',[],1,Inf,"",'legacy params.wavelet_voices_per_octave=12');
catalog = add(catalog, 'params.dual.frequency.wavelet_name','dual','all','frequency','Frequency','Expert','edit','Wavelet name', ...
    'Wavelet-family metadata for time-frequency analysis.','string',"amor",'',[],[],[],"",'legacy params.wavelet_name=amor');
catalog = add(catalog, 'params.dual.camera_source_override','dual','all','input','Overrides','Expert','table','Camera source override', ...
    'Optional expert struct overriding resolved camera sources.','struct',struct(),'',[],[],[],"",'legacy camera_source_override');
catalog = add(catalog, 'params.dual.stim_context_override','dual','all','stim','Overrides','Expert','table','Stimulus context override', ...
    'Optional expert struct overriding resolved stimulus metadata.','struct',struct(),'',[],[],[],"",'legacy stim_context_override');

% Record scheduling. Every legacy decision is explicitly represented.
catalog = add(catalog, 'record.cycles','all','record','input','Record','Basic','table','Cycles', ...
    'Optional Cycle-name allowlist; empty includes discovered cycles.','string_vector',strings(0,1),'',[],[],[],"",'legacy cycles');
catalog = add(catalog, 'record.reference_cycle_name','all','record','roi','Reference ROI','Basic','edit','Reference cycle', ...
    'Cycle used to obtain a shared ROI when required.','string',"Cycle1",'',[],[],[],"",'legacy reference_cycle_name');
catalog = add(catalog, 'record.reference_roi_path','all','record','roi','Reference ROI','Basic','path','Reference ROI path', ...
    'Explicit existing reference ROI result folder or file.','path',"",'',[],[],[],"",'legacy reference_roi_path');
catalog = add(catalog, 'record.reuse_reference_roi','all','record','roi','Reference ROI','Basic','checkbox','Reuse reference ROI', ...
    'Reuse a compatible existing reference ROI when available.','logical',true,'',[],[],[],"",'legacy reuse_reference_roi');
catalog = add(catalog, 'record.redraw_reference_roi','all','record','roi','Reference ROI','Advanced','checkbox','Redraw reference ROI', ...
    'Force the reference ROI to be redrawn.','logical',false,'',[],[],[],"",'legacy redraw_reference_roi');
catalog = add(catalog, 'record.reference_roi_only','dual','record','roi','Reference ROI','Advanced','checkbox','Reference ROI only', ...
    'Stop the reference-cycle job after the minimum stages needed to create ROI.','logical',false,'',[],[],[],"",'new explicit efficient reference policy');
catalog = add(catalog, 'record.reference_roi_only','ap','record','roi','Reference ROI','Advanced','readonly','Reference ROI only', ...
    'Visible for protocol compatibility, but the AP Record scheduler cannot yet stop after ROI.','logical',false,'',[],[],[],"",'AP Record ROI-only scheduling not yet migrated');
catalog(end).editable = false;
catalog(end).default_rule = "unavailable in AP Record scheduler";
catalog = add(catalog, 'record.include_reference_cycle','all','record','input','Record','Basic','checkbox','Include reference cycle', ...
    'Include the reference cycle in ordinary batch results.','logical',false,'',[],[],[],"",'legacy include_reference_cycle');
catalog = add(catalog, 'record.skip_existing','all','record','input','Record','Basic','checkbox','Skip existing results', ...
    'Skip cycles with compatible completed outputs. This is explicit in AAA rather than inferred from preset.','logical',false,'',[],[],[],"",'legacy [] with motion_only inference removed');
catalog = add(catalog, 'record.stop_on_error','all','record','input','Record','Basic','checkbox','Stop on error', ...
    'Stop the Record run at the first failed cycle.','logical',true,'',[],[],[],"",'legacy stop_on_error');
catalog = add(catalog, 'record.write_diary','all','record','export','Logging','Advanced','checkbox','Write batch diary', ...
    'Write the Record-level MATLAB diary/log.','logical',true,'',[],[],[],"",'legacy write_diary');
catalog = add(catalog, 'record.record_average','dual','record','comparison','Record analysis','Basic','checkbox','Run Record average', ...
    'Run the existing Dual Record-level averaging analysis after successful cycles.','logical',false,'',[],[],[],"",'legacy record_average');
catalog = add(catalog, 'record.record_average_only','dual','record','comparison','Record analysis','Advanced','checkbox','Record average only', ...
    'Skip Cycle analysis and run only Record averaging from existing results.','logical',false,'',[],[],[],"",'legacy record_average_only');
catalog = add(catalog, 'record.record_average','ap','record','ap_statistics','Record analysis','Basic','checkbox','Run AP Record average', ...
    'Run shared voltage Record-level averaging, tuning, statistics, and figures after Cycle processing.','logical',false,'',[],[],[],"",'AAA Record_analysis3');
catalog = add(catalog, 'record.record_average_only','ap','record','ap_statistics','Record analysis','Advanced','checkbox','AP Record average only', ...
    'Skip AP Cycle computation and analyze automatically resolved existing Cycle results.','logical',false,'',[],[],[],"",'AAA Record_analysis3');
catalog = add(catalog, 'params.ap.record_frequency.enabled','ap','record','ap_statistics','Record frequency','Advanced','checkbox','Record FFT/wavelet', ...
    'For flash Records, compute FFT and representative CWT from the Record-average sensitivity trace.','logical',true,'',[],[],[],"",'Dual Record frequency behavior');
catalog = add(catalog, 'params.ap.record_frequency.min_freq_hz','ap','record','ap_statistics','Record frequency','Advanced','numeric','Record minimum frequency', ...
    'Lower frequency bound used for Record FFT peak reporting.','double',0.5,'Hz',[],0,Inf,"params.ap.record_frequency.enabled",'Dual min_freq_hz=0.5');
catalog = add(catalog, 'params.ap.record_frequency.max_freq_hz','ap','record','ap_statistics','Record frequency','Advanced','numeric','Record maximum frequency', ...
    'Upper frequency bound, clamped to below the saved Nyquist frequency.','double',100,'Hz',[],eps,Inf,"params.ap.record_frequency.enabled",'Dual max_freq_hz=100');
catalog = add(catalog, 'params.ap.record_frequency.wavelet_voices_per_octave','ap','record','ap_statistics','Record frequency','Expert','numeric','Record wavelet voices/octave', ...
    'CWT voices per octave for the representative Record-average ROI.','integer',12,'',[],1,Inf,"params.ap.record_frequency.enabled",'Dual wavelet voices=12');
catalog = add(catalog, 'params.ap.record_frequency.wavelet_name','ap','record','ap_statistics','Record frequency','Expert','edit','Record wavelet', ...
    'Wavelet name used by MATLAB cwt.','string',"amor",'',[],[],[],"params.ap.record_frequency.enabled",'Dual wavelet=amor');
catalog = add(catalog, 'record.reuse_saved_peaks','dual','record','peak','Reuse','Advanced','checkbox','Reuse saved peaks', ...
    'Prefer accepted saved peaks in analysis-only Record jobs.','logical',true,'',[],[],[],"",'legacy reuse_saved_peaks');
catalog = add(catalog, 'record.run_motion','dual','record','motion','Record','Basic','checkbox','Run motion stage', ...
    'Expose the legacy Record-level motion decision; the resolved section table remains authoritative.','logical',true,'',[],[],[],"",'legacy run_motion');
catalog = add(catalog, 'record.reference_offset_mode','dual','record','registration','Reference ROI','Advanced','dropdown','Reference offset mode', ...
    'Registration mode used while building the reference ROI.','enum',"none",'',["none","manual_points","matlab_register"],[],[],"",'legacy reference_offset_mode');
catalog = add(catalog, 'record.cycle_offset_mode','dual','record','registration','Record','Advanced','dropdown','Cycle offset mode', ...
    'Registration mode applied to ordinary cycles.','enum',"none",'',["none","manual_points","matlab_register"],[],[],"",'legacy cycle_offset_mode');
catalog = add(catalog, 'record.reuse_offset','dual','record','registration','Record','Advanced','table','Record reuse offset', ...
    'Default [x y] offset applied when no new registration is requested.','numeric_vector',[0 0],'pixels',[],[],[],"",'legacy record reuse_offset');
catalog = add(catalog, 'record.output_root','dual','record','export','Paths','Advanced','edit','Record output root', ...
    'Result-root folder name used by Dual Record scheduling.','string',"Dual_analysis3",'',[],[],[],"",'legacy output_root');
catalog = add(catalog, 'record.output_root','ap','record','export','Paths','Advanced','edit','Record output root', ...
    'Result-root folder name used by AP Record scheduling.','string',"AP_analysis3",'',[],[],[],"",'new AP Record default');
catalog = add(catalog, 'record.run_tag','all','record','export','Paths','Advanced','edit','Record run tag', ...
    'Optional tag for Record analysis-only output folders.','string',"",'',[],[],[],"",'legacy run_tag');

catalog = mark_compatibility_locked_parameters(catalog);

if nargin >= 1 && ~isempty(mode)
    mode = lower(strtrim(string(mode)));
    catalog = catalog([catalog.mode] == "all" | [catalog.mode] == mode);
end
if nargin >= 2 && ~isempty(scope)
    scope = lower(strtrim(string(scope)));
    catalog = catalog([catalog.scope] == "all" | [catalog.scope] == scope);
end

if nargin >= 1 && ~isempty(mode)
    keys = [catalog.key];
    if numel(unique(keys)) ~= numel(keys)
        error('AAA:Schema:DuplicateParameterKey', ...
            'The filtered parameter catalog contains duplicate keys.');
    end
end
end

function catalog = mark_compatibility_locked_parameters(catalog)
% Keep every default visible while preventing controls that the migrated
% backend cannot yet apply from pretending to be operational.
locked_exact = [ ...
    "params.ap.motion.init_batch"];
locked_prefixes = strings(0,1);
for idx = 1:numel(catalog)
    key = catalog(idx).key;
    is_locked = ismember(key, locked_exact) ...
        || any(startsWith(key, locked_prefixes));
    if ~is_locked
        continue;
    end
    catalog(idx).editable = false;
    catalog(idx).ui_control = "readonly";
    if strlength(catalog(idx).default_rule) == 0
        catalog(idx).default_rule = ...
            "backend parameter migration pending";
    end
end
for idx = 1:numel(catalog)
    if catalog(idx).value_type == "logical" && ~catalog(idx).editable
        % Read-only logical policies are still displayed as checkboxes;
        % the App blocks edits while keeping the actual frozen state public.
        catalog(idx).ui_control = "checkbox";
    end
end
end

function catalog = add_isi_parameters(catalog)
base = 'params.ap.isi.';
rows = {
 'frame_index_origin_is_zero_time','logical',true,'checkbox','Frame 1 is time zero','',[],[], 'Basic';
 'window_s','double',10,'numeric','Firing-rate window','s',eps,Inf,'Advanced';
 'window_step_s','double',5,'numeric','Firing-rate step','s',eps,Inf,'Advanced';
 'rate_drift_slope_threshold_hz_per_min','double',0.05,'numeric','Rate-drift slope threshold','Hz/min',0,Inf,'Expert';
 'rate_drift_half_diff_fraction','double',0.5,'numeric','Rate-drift half-difference fraction','fraction',0,Inf,'Expert';
 'min_spike_count','integer',10,'numeric','Minimum spike count','',0,Inf,'Advanced';
 'suspicious_short_isi_ms','double',1.0,'numeric','Suspicious short ISI','ms',0,Inf,'Expert';
 'suspicious_short_isi_fraction_threshold','double',0.05,'numeric','Suspicious short-ISI fraction','fraction',0,1,'Expert';
 'min_frames_per_burst_interval','integer',3,'numeric','Minimum frames per burst interval','frames',1,Inf,'Expert';
 'burst_start_isi_threshold_ms','double',20,'numeric','Burst start ISI','ms',0,Inf,'Basic';
 'burst_end_isi_threshold_ms','double',NaN,'numeric','Burst end ISI','ms',0,Inf,'Advanced';
 'min_burst_end_isi_threshold_ms','double',50,'numeric','Minimum burst end ISI','ms',0,Inf,'Expert';
 'burst_end_to_start_ratio','double',3,'numeric','Burst end/start ratio','',0,Inf,'Expert';
 'min_spikes_per_burst','integer',3,'numeric','Minimum spikes per burst','',2,Inf,'Basic';
 'min_fast_isi_count_per_burst','double',NaN,'numeric','Minimum fast ISIs per burst','',1,Inf,'Advanced';
 'max_burst_duration_ms','double',Inf,'numeric','Maximum burst duration','ms',0,Inf,'Advanced';
 'require_quiescence_boundaries','logical',true,'checkbox','Require quiescent boundaries','',[],[],'Basic';
 'allow_edge_bursts','logical',false,'checkbox','Allow edge bursts','',[],[],'Advanced';
 'high_short_isi_fraction_threshold','double',0.50,'numeric','High short-ISI fraction','fraction',0,1,'Expert';
 'min_burst_count_for_periodicity','integer',5,'numeric','Minimum bursts for periodicity','',1,Inf,'Expert';
 'low_burst_fraction_threshold','double',0.10,'numeric','Low burst-fraction threshold','fraction',0,1,'Expert';
 'high_burst_fraction_threshold','double',0.30,'numeric','High burst-fraction threshold','fraction',0,1,'Expert';
 'low_CV_IBI_threshold','double',0.50,'numeric','Low CV-IBI threshold','',0,Inf,'Expert';
 'high_CV_IBI_threshold','double',1.00,'numeric','High CV-IBI threshold','',0,Inf,'Expert';
 'low_LvR_threshold','double',0.80,'numeric','Low LvR threshold','',0,Inf,'Expert';
 'high_LvR_threshold','double',1.20,'numeric','High LvR threshold','',0,Inf,'Expert';
 'LvR_refractory_R_s','double',0.005,'numeric','LvR refractory R','s',0,Inf,'Expert';
 'make_per_neuron_figures','logical',true,'checkbox','Per-neuron ISI figures','',[],[],'Advanced';
 'figures_visible','logical',false,'checkbox','Show ISI figures','',[],[],'Advanced';
 'isi_histogram_num_bins','integer',100,'numeric','ISI histogram bins','',1,Inf,'Expert';
 'ibi_histogram_num_bins','integer',20,'numeric','IBI histogram bins','',1,Inf,'Expert';
 'isi_histogram_xlim_log10_ms','numeric_vector',[],'table','ISI histogram x limits','log10(ms)',[],[],'Expert';
 'ibi_histogram_xlim_s','numeric_vector',[],'table','IBI histogram x limits','s',[],[],'Expert';
 'run_threshold_sensitivity','logical',true,'checkbox','Threshold sensitivity analysis','',[],[],'Advanced';
 'sensitivity_burst_start_thresholds_ms','numeric_vector',[10 20 30],'table','Sensitivity start thresholds','ms',0,Inf,'Expert';
 'sensitivity_scale_end_threshold','logical',true,'checkbox','Scale end threshold','',[],[],'Expert'};
for idx = 1:size(rows,1)
    catalog = add(catalog, [base rows{idx,1}], 'ap','all','ap_statistics','ISI phenotype', ...
        rows{idx,9},rows{idx,4},rows{idx,5},'AP ISI/phenotype parameter.', ...
        rows{idx,2},rows{idx,3},rows{idx,6},[],rows{idx,7},rows{idx,8},"", ...
        "legacy default_isi_stat_params_revised."+string(rows{idx,1}));
end
end

function catalog = add(catalog, key, mode, scope, section, group, level, control, label, description, value_type, default, units, choices, minimum, maximum, visible_when, legacy_source)
entry = empty_entry();
entry.key = string(key);
entry.mode = string(mode);
entry.scope = string(scope);
entry.section = string(section);
entry.group = string(group);
entry.ui_level = string(level);
entry.ui_control = string(control);
entry.ui_label = string(label);
entry.description = string(description);
entry.value_type = string(value_type);
entry.default = default;
entry.units = string(units);
if isempty(choices)
    entry.choices = strings(0,1);
else
    entry.choices = string(choices(:));
end
entry.minimum = minimum;
entry.maximum = maximum;
entry.visible_when = string(visible_when);
entry.legacy_source = string(legacy_source);
entry.public = true;
catalog(end+1,1) = entry;
end

function entry = empty_entry()
entry = struct( ...
    'key', "", ...
    'mode', "all", ...
    'scope', "all", ...
    'section', "", ...
    'group', "", ...
    'ui_level', "Basic", ...
    'ui_control', "edit", ...
    'ui_label', "", ...
    'description', "", ...
    'value_type', "string", ...
    'default', [], ...
    'units', "", ...
    'choices', strings(0,1), ...
    'minimum', [], ...
    'maximum', [], ...
    'visible_when', "", ...
    'legacy_source', "", ...
    'editable', true, ...
    'default_rule', "", ...
    'public', true);
end
