function receipt = build_receipt(ctx)
%BUILD_RECEIPT Build a lightweight orchestration-only section receipt.
% Deliberately excluded: request parameter trees, channel data/results, and
% output payloads. Scientific outputs remain authoritative in result files.

if ~isstruct(ctx) || ~isscalar(ctx) || ~isfield(ctx, 'execution')
    error('AAA:Sections:InvalidContext', ...
        'ctx must be one scalar section execution context.');
end

history = ctx.execution.history;
completed_sections = sections_in_state(history, "completed");
reused_sections = sections_in_state(history, "reused");
skipped_sections = sections_in_state(history, "skipped");

receipt = struct( ...
    'receipt_schema_version', "1.0.0", ...
    'status', string(ctx.execution.status), ...
    'mode', string(ctx.mode), ...
    'scope', string(ctx.scope), ...
    'input_path', string(ctx.input_path), ...
    'output_path', string(ctx.output_path), ...
    'started_at', ctx.execution.started_at, ...
    'completed_at', ctx.execution.completed_at, ...
    'completed_sections', completed_sections, ...
    'reused_sections', reused_sections, ...
    'skipped_sections', skipped_sections, ...
    'failed_section', string(ctx.execution.failed_section), ...
    'failed_channel', string(ctx.execution.failed_channel), ...
    'error', lightweight_error(ctx.execution.error), ...
    'section_status', summarize_sections(history), ...
    'channel_status', summarize_channels(ctx.channels));
end

function sections = sections_in_state(history, state)
sections = strings(0,1);
if isempty(history)
    return;
end
states = string({history.state})';
names = string({history.section})';
sections = unique(names(states == state), 'stable');
end

function status = summarize_sections(history)
status = struct();
for idx = 1:numel(history)
    name = char(history(idx).section);
    if isempty(name)
        continue;
    end
    status.(name) = struct( ...
        'action', string(history(idx).action), ...
        'state', string(history(idx).state), ...
        'started_at', history(idx).started_at, ...
        'completed_at', history(idx).completed_at, ...
        'message', string(history(idx).message), ...
        'channels', string(history(idx).channels(:)), ...
        'failed_channel', string(history(idx).failed_channel), ...
        'error', lightweight_error(history(idx).error));
end
end

function summary = summarize_channels(channels)
template = struct( ...
    'role', "", ...
    'camera_index', NaN, ...
    'state', "", ...
    'section', "", ...
    'message', "", ...
    'error', empty_error());
summary = repmat(template, numel(channels), 1);
for idx = 1:numel(channels)
    summary(idx) = template;
    summary(idx).role = string(channels(idx).profile.role);
    summary(idx).camera_index = channels(idx).camera_index;
    summary(idx).state = string(channels(idx).status.state);
    summary(idx).section = string(channels(idx).status.section);
    summary(idx).message = string(channels(idx).status.message);
    summary(idx).error = lightweight_error(channels(idx).status.error);
end
end

function value = lightweight_error(input_value)
value = empty_error();
if isa(input_value, 'MException')
    value.identifier = string(input_value.identifier);
    value.message = string(input_value.message);
elseif isstruct(input_value) && isscalar(input_value)
    if isfield(input_value, 'identifier')
        value.identifier = string(input_value.identifier);
    end
    if isfield(input_value, 'message')
        value.message = string(input_value.message);
    end
end
end

function value = empty_error()
value = struct('identifier',"",'message',"");
end
