function ctx = create_context(request, runtime)
%CREATE_CONTEXT Build the shared, mode-neutral section execution context.
% The validated channel profile is the sole authority for role, frame rate,
% orientation, and effective algorithm parameters. It does not retain the
% complete request. Scientific arrays remain in channel.data/results and are
% never copied into the orchestration receipt.

if nargin < 2 || isempty(runtime)
    runtime = struct();
end
if ~isstruct(runtime) || ~isscalar(runtime)
    error('AAA:Sections:InvalidRuntime', ...
        'runtime must be one scalar struct.');
end

[request, report] = aaa.schema.validate_request(request);
if ~report.valid
    error('AAA:Sections:InvalidRequest', '%s', ...
        char(strjoin(string(report.errors), newline)));
end

mode = string(request.mode);
switch mode
    case "ap"
        channels = build_ap_channel(request);
    case "dual"
        channels = build_dual_channels(request);
    otherwise
        error('AAA:Sections:InvalidMode', ...
            'Unsupported analysis mode: %s.', mode);
end

ctx = struct( ...
    'context_schema_version', "1.0.0", ...
    'mode', mode, ...
    'scope', string(request.scope), ...
    'request', request, ...
    'input_path', string(request.input_path), ...
    'output_path', string(request.workflow.output_path), ...
    'runtime', runtime, ...
    'channels', channels, ...
    'shared', struct('data',struct(),'results',struct(),'output_files',struct()), ...
    'warnings', string(report.warnings(:)), ...
    'execution', empty_execution_state());
end

function channel = build_ap_channel(request)
profile = make_profile(request, "voltage");
channel = channel_template();
channel.camera_index = double(request.params.ap.camera_index);
channel.source = string(request.input_path);
channel.profile = profile;
end

function channels = build_dual_channels(request)
camera_roles = [ ...
    string(request.params.dual.camera1_role), ...
    string(request.params.dual.camera2_role)];
canonical_roles = ["voltage", "calcium"];
channels = repmat(channel_template(), 1, numel(canonical_roles));
for idx = 1:numel(canonical_roles)
    role = canonical_roles(idx);
    camera_index = find(camera_roles == role, 1, 'first');
    if isempty(camera_index)
        error('AAA:Sections:MissingChannelRole', ...
            'Dual request does not assign a camera to role "%s".', role);
    end
    channels(idx).camera_index = camera_index;
    channels(idx).source = string(request.input_path);
    channels(idx).profile = make_profile(request, role);
end
end

function channel = channel_template()
channel = struct( ...
    'camera_index', NaN, ...
    'source', "", ...
    'profile', struct(), ...
    'data', struct(), ...
    'results', struct(), ...
    'output_files', struct(), ...
    'status', struct( ...
        'state', "pending", ...
        'section', "", ...
        'message', "", ...
        'error', empty_error()));
end

function profile = make_profile(request, role)
mode = string(request.mode);
common_params = request.params.common;
switch mode
    case "ap"
        mode_params = request.params.ap;
        frame_rate = mode_params.freq;
        transpose_before_analysis = mode_params.transpose_before_analysis;
    case "dual"
        mode_params = request.params.dual;
        frame_rate = mode_params.(char(role + "_frame_rate"));
        transpose_before_analysis = ...
            mode_params.(char(role + "_transpose_movie"));
end

profile = struct( ...
    'role', role, ...
    'frame_rate', double(frame_rate), ...
    'transpose_before_analysis', logical(transpose_before_analysis), ...
    'motion', bind_motion_profile(mode, role, common_params, mode_params), ...
    'roi', bind_roi_profile(mode, common_params, mode_params), ...
    'trace', bind_trace_profile(mode, role, frame_rate, mode_params), ...
    'peak', bind_peak_profile(mode, role, frame_rate, mode_params));
end

function motion = bind_motion_profile(mode, role, common_params, mode_params)
motion = common_params.motion;
switch mode
    case "ap"
        motion.max_shift = mode_params.motion.rigid_max_shift;
        motion.nonrigid = false;
        motion.nonrigid_options = struct();
    case "dual"
        motion.max_shift = mode_params.motion.max_shift;
        motion.nonrigid = false;
        motion.nonrigid_options = struct();
        motion.auto_reuse_previous_shift = ...
            logical(mode_params.motion.auto_reuse_previous_shift);
        if role == "calcium"
            % Empty means no independently selected calcium shift file.
            % Shared-shift coordination belongs to the motion section.
            motion.saved_shift_file = ...
                string(mode_params.motion.saved_calcium_shift_file);
        end
end
end

function roi = bind_roi_profile(mode, common_params, mode_params)
if mode == "ap"
    map_bin = mode_params.bin;
else
    map_bin = mode_params.map_bin;
end
roi = struct( ...
    'frame_size', [], ...
    'map', struct('bin',map_bin), ...
    'background', common_params.background);
end

function trace = bind_trace_profile(mode, role, frame_rate, mode_params)
if mode == "ap"
    noise_reference = struct( ...
        'method', "wdenoise", ...
        'level', mode_params.Dnlevel, ...
        'denoising_method', string(mode_params.Dnmethods), ...
        'wavelet_name', string(mode_params.Wavename));
    bleach_mode = string(mode_params.bleachmode);
    smoothing = struct('method',"none",'window',1,'dimension',1);
elseif role == "voltage"
    noise_reference = struct( ...
        'method', "wdenoise", ...
        'level', mode_params.noise.voltage_wavelet_level, ...
        'denoising_method', string(mode_params.noise.voltage_wavelet_method), ...
        'wavelet_name', string(mode_params.noise.voltage_wavelet_name));
    bleach_mode = string(mode_params.bleach_mode_voltage);
    smoothing = struct('method',"none",'window',1,'dimension',1);
else
    cutoff_hz = double(mode_params.noise.calcium_cutoff_hz);
    normalized_cutoff = min(0.49, 2 * cutoff_hz / max(double(frame_rate), 1));
    noise_reference = struct( ...
        'method', "butterworth_filtfilt", ...
        'order', mode_params.noise.calcium_filter_order, ...
        'cutoff_hz', cutoff_hz, ...
        'normalized_cutoff', normalized_cutoff);
    bleach_mode = string(mode_params.bleach_mode_calcium);
    smoothing = struct( ...
        'method', "movmean", ...
        'window', mode_params.calcium_smoothing_window, ...
        'dimension', 1);
end

trace = struct( ...
    'noise_reference', noise_reference, ...
    'bleach', struct( ...
        'mode', bleach_mode, ...
        'frame_rate', double(frame_rate), ...
        'time_axis', []), ...
    'smoothing', smoothing);
end

function peak = bind_peak_profile(mode, role, frame_rate, mode_params)
peak = struct();
if role ~= "voltage"
    return;
end
switch mode
    case "ap"
        min_distance = mode_params.peak_min_distance_frames;
        if isempty(min_distance)
            min_distance = max(2, round(0.003 * double(frame_rate)));
        end
        peak = struct( ...
            'trace_stage', "sensitivity", ...
            'polarity_mode', string(mode_params.peak_polarity_mode), ...
            'global_polarity', 1, ...
            'roi_polarity', [], ...
            'min_peak_prominence', mode_params.peak_min_prominence, ...
            'min_peak_prominence_mode', ...
                string(mode_params.peak_min_prominence_mode), ...
            'min_peak_distance_frames', min_distance, ...
            'min_peak_height', mode_params.peak_min_height, ...
            'run_manual_edit', logical(mode_params.run_manual_peak_refinement));
    case "dual"
        min_distance = mode_params.voltage_peak_min_distance_frames;
        if isempty(min_distance)
            min_distance = max(2, round(0.01 * double(frame_rate)));
        end
        peak = struct( ...
            'trace_stage', "sensitivity", ...
            'polarity_mode', string(mode_params.voltage_peak_polarity_mode), ...
            'global_polarity', mode_params.voltage_polarity, ...
            'roi_polarity', {mode_params.voltage_peak_roi_polarity}, ...
            'min_peak_prominence', mode_params.voltage_peak_min_prominence, ...
            'min_peak_prominence_mode', ...
                string(mode_params.voltage_peak_min_prominence_mode), ...
            'min_peak_distance_frames', min_distance, ...
            'min_peak_height', mode_params.voltage_peak_min_height, ...
            'run_manual_edit', logical(mode_params.run_manual_voltage_peak_edit));
end
end

function execution = empty_execution_state()
execution = struct( ...
    'status', "pending", ...
    'plan', struct(), ...
    'history', empty_history(), ...
    'current_section', "", ...
    'current_action', "", ...
    'current_channel', "", ...
    'started_at', NaT, ...
    'completed_at', NaT, ...
    'failed_section', "", ...
    'failed_channel', "", ...
    'error', empty_error(), ...
    'exception', []);
end

function history = empty_history()
history = repmat(struct( ...
    'section', "", ...
    'action', "", ...
    'state', "", ...
    'started_at', NaT, ...
    'completed_at', NaT, ...
    'message', "", ...
    'channels', strings(0,1), ...
    'failed_channel', "", ...
    'error', empty_error()), 0, 1);
end

function value = empty_error()
value = struct('identifier',"",'message',"");
end
