function [movie_corrected, application] = apply_motion(movie_3d, model)
%APPLY_MOTION Apply one already-estimated rigid shift field.
%   Shift count must exactly equal movie frame count. This function never
%   truncates, pads, or temporally interpolates a shift field.
% Inputs:
%   movie_3d Nonempty numeric/logical [ncols x nrows x frames] movie.
%   model Scalar struct containing shifts and NoRMCorre options; model
%         geometry and shift count must match the movie exactly.
% Outputs:
%   movie_corrected Single [ncols x nrows x frames] corrected movie.
%   application Scalar struct describing input/output geometry and counts.

if (~isnumeric(movie_3d) && ~islogical(movie_3d)) ...
        || isempty(movie_3d) || ndims(movie_3d) > 3
    error('AAA:Algorithms:InvalidMotionMovie', ...
        'Motion input must be a nonempty 2-D or 3-D numeric movie.');
end
if ~isstruct(model) || ~isscalar(model) ...
        || ~isfield(model, 'shifts') || ~isfield(model, 'options')
    error('AAA:Algorithms:InvalidMotionModel', ...
        'Motion model must contain shifts and options.');
end

[ncols, nrows, nframes] = size(movie_3d);
shift_count = numel(model.shifts);
if shift_count ~= nframes
    error('AAA:Algorithms:MotionShiftFrameMismatch', ...
        ['Motion model contains %d shifts but the movie has %d frames. ' ...
         'Shift fields are not truncated or interpolated.'], ...
        shift_count, nframes);
end
if isfield(model.options, 'd1') && ~isempty(model.options.d1) ...
        && double(model.options.d1) ~= ncols
    error('AAA:Algorithms:MotionShiftGeometryMismatch', ...
        'Motion options d1=%d but movie dimension 1 is %d.', ...
        model.options.d1, ncols);
end
if isfield(model.options, 'd2') && ~isempty(model.options.d2) ...
        && double(model.options.d2) ~= nrows
    error('AAA:Algorithms:MotionShiftGeometryMismatch', ...
        'Motion options d2=%d but movie dimension 2 is %d.', ...
        model.options.d2, nrows);
end

movie_corrected = apply_shifts(single(movie_3d), model.shifts, model.options);
if size(movie_corrected, 3) ~= nframes
    error('AAA:Algorithms:MotionOutputFrameMismatch', ...
        'Motion application changed the frame count from %d to %d.', ...
        nframes, size(movie_corrected, 3));
end
application = struct( ...
    'frame_count', nframes, ...
    'frame_size', [ncols, nrows], ...
    'shift_count', shift_count, ...
    'input_class', string(class(movie_3d)), ...
    'output_class', string(class(movie_corrected)), ...
    'applied_at', datetime('now'));
end
