function [traces, info] = extract_roi_traces(movie, roi_mask, profile)
%EXTRACT_ROI_TRACES Extract mean traces for supplied positive ROI labels.
% Each output column corresponds to the same-position entry in info.labels.
% Dual channel pairing remains a section responsibility: this atom neither
% intersects channel labels nor truncates, pads, or interpolates traces.
% Inputs:
%   movie Numeric/logical movie accepted by normalize_movie_matrix.
%   roi_mask Real [ncols x nrows] integer label matrix: 0 is background;
%            each positive integer identifies one ROI.
%   profile Scalar bound profile requiring role and roi.frame_size.
% Outputs:
%   traces Double [frames x ROI], ordered by ascending positive label.
%   info Scalar struct containing labels, pixel counts, and exact geometry.

[movie_matrix, movie_info] = normalize_movie_matrix( ...
    movie, profile);
roi_mask = validate_roi_mask(roi_mask, movie_info.frame_size);

labels = unique(double(roi_mask(:)), 'sorted');
labels = labels(labels > 0);
traces = zeros(movie_info.frame_count, numel(labels));
pixel_counts = zeros(1, numel(labels));
for label_idx = 1:numel(labels)
    selected = roi_mask(:) == labels(label_idx);
    pixel_counts(label_idx) = nnz(selected);
    traces(:, label_idx) = mean( ...
        movie_matrix(selected, :), 1, 'double')';
end

info = struct( ...
    'role', movie_info.role, ...
    'profile', profile, ...
    'labels', reshape(labels, 1, []), ...
    'pixel_counts', pixel_counts, ...
    'frame_size', movie_info.frame_size, ...
    'frame_count', movie_info.frame_count, ...
    'method', "mean of pixels carrying each positive integer label", ...
    'pairing_rule', "none; channel pairing belongs to the section", ...
    'alignment_rule', movie_info.alignment_rule);
end

function roi_mask = validate_roi_mask(roi_mask, frame_size)
if (~isnumeric(roi_mask) && ~islogical(roi_mask)) || ~isreal(roi_mask) ...
        || ~ismatrix(roi_mask) || ~isequal(size(roi_mask), frame_size)
    error('AAA:Algorithms:InvalidRoiMask', ...
        'ROI mask must be one real [%d %d] label matrix.', ...
        frame_size(1), frame_size(2));
end
if any(~isfinite(double(roi_mask(:)))) ...
        || any(double(roi_mask(:)) < 0) ...
        || any(double(roi_mask(:)) ~= round(double(roi_mask(:))))
    error('AAA:Algorithms:InvalidRoiMaskLabels', ...
        'ROI mask labels must be finite nonnegative integers.');
end
end
