function [result, info] = remove_background(movie, roi_mask, profile)
%REMOVE_BACKGROUND Apply the current frozen Dual local-background formula.
% PROFILE is the complete bound channel profile. Role is read only from
% profile.role; effective settings are profile.roi.background. This atom performs no
% file I/O, UI work, progress reporting, or parallel-pool management.
% Inputs:
%   movie Numeric/logical movie accepted by normalize_movie_matrix.
%   roi_mask Real [ncols x nrows] integer label matrix: 0 is background;
%            positive labels identify ROIs.
%   profile Scalar bound profile requiring role, roi.frame_size, and the
%           documented roi.background parameters. It contains no request.
% Outputs:
%   result Background/raw/fitted trace matrices, each [frames x ROI], plus
%          the frozen-orientation background label mask.
%   info Scalar struct recording labels, geometry, and selection rules.

require_background_profile(profile);
[movie_matrix, movie_info] = normalize_movie_matrix( ...
    movie, profile);
roi_mask = validate_roi_mask(roi_mask, movie_info.frame_size);

params = profile.roi.background;
inner_distance = double(params.inner_distance);
outer_distance = double(params.outer_distance);
background_fraction = double(params.background_fraction);
fit_span = double(params.fit_span);
fit_method = char(string(params.fit_method));

labels = unique(double(roi_mask(:)), 'sorted');
labels = labels(labels > 0);
nframes = movie_info.frame_count;
nrois = numel(labels);
background_raw = zeros(nframes, nrois);
background_fitted = zeros(nframes, nrois);
roi_minus_background_raw = zeros(nframes, nrois);
roi_minus_background_fitted = zeros(nframes, nrois);

% Frozen remove_background preallocated [nrows x ncols] although the ROI
% label mask is [ncols x nrows]. Preserve that saved-output orientation.
frame_size = movie_info.frame_size;
background_mask = zeros(frame_size(2), frame_size(1));
background_mask_cells = cell(nrois, 1);

inner_element = strel('disk', inner_distance);
outer_element = strel('disk', outer_distance);
for label_idx = 1:nrois
    roi_pixels = roi_mask == labels(label_idx);
    inner_mask = imdilate(roi_pixels, inner_element);
    outer_mask = imdilate(roi_pixels, outer_element);
    annulus_mask = outer_mask & ~inner_mask;

    average_image = zeros(size(annulus_mask));
    average_image(annulus_mask) = mean( ...
        movie_matrix(annulus_mask(:), :), 2);
    sorted_pixels = sort(average_image(annulus_mask));
    threshold_index = round(numel(sorted_pixels) * background_fraction);
    if threshold_index < 1
        error('AAA:Algorithms:InsufficientBackgroundPixels', ...
            ['ROI label %g has %d annulus pixels; round(N*fraction) is zero ' ...
             'for background_fraction=%g.'], ...
            labels(label_idx), numel(sorted_pixels), background_fraction);
    end
    threshold_value = sorted_pixels(threshold_index);
    selected_background = ...
        (average_image <= threshold_value) & annulus_mask;
    background_mask_cells{label_idx} = selected_background;

    background_trace = mean( ...
        movie_matrix(selected_background(:), :), 1);
    fitted_trace = smooth( ...
        background_trace, fit_span, fit_method)';
    roi_trace = mean(movie_matrix(roi_pixels(:), :), 1);

    background_raw(:, label_idx) = background_trace;
    background_fitted(:, label_idx) = fitted_trace;
    roi_minus_background_raw(:, label_idx) = ...
        roi_trace - background_trace;
    roi_minus_background_fitted(:, label_idx) = ...
        roi_trace - fitted_trace;
end

for label_idx = 1:nrois
    background_mask(background_mask_cells{label_idx}) = labels(label_idx);
end

result = struct( ...
    'background_raw', background_raw, ...
    'background_fitted', background_fitted, ...
    'roi_minus_background_raw', roi_minus_background_raw, ...
    'roi_minus_background_fitted', roi_minus_background_fitted, ...
    'background_mask', background_mask);
info = struct( ...
    'role', movie_info.role, ...
    'profile', profile, ...
    'labels', reshape(labels, 1, []), ...
    'frame_size', frame_size, ...
    'frame_count', nframes, ...
    'annulus_rule', "imdilate(outer) & ~imdilate(inner)", ...
    'selection_rule', ...
        "lowest mean-intensity fraction; threshold ties retained", ...
    'threshold_index_rule', "round(N * background_fraction)", ...
    'fit_rule', "smooth(background, fit_span, fit_method)", ...
    'dual_bg_removed_stage', "roi_minus_background_fitted", ...
    'background_mask_size', size(background_mask), ...
    'background_mask_orientation', ...
        "frozen [nrows ncols], transposed from ROI-mask [ncols nrows]", ...
    'alignment_rule', movie_info.alignment_rule);
end

function require_background_profile(profile)
required = {'inner_distance', 'outer_distance', ...
    'background_fraction', 'fit_span', 'fit_method'};
if ~isstruct(profile) || ~isscalar(profile) ...
        || ~all(isfield(profile, {'role','roi'})) ...
        || ~isstruct(profile.roi) || ~isscalar(profile.roi) ...
        || ~isfield(profile.roi, 'background') ...
        || ~isstruct(profile.roi.background) ...
        || ~isscalar(profile.roi.background) ...
        || ~all(isfield(profile.roi.background, required))
    error('AAA:Algorithms:InvalidBackgroundProfile', ...
        'profile.roi.background requires: %s.', strjoin(required, ', '));
end
params = profile.roi.background;
if ~isnumeric(params.inner_distance) ...
        || ~isscalar(params.inner_distance) ...
        || ~isfinite(params.inner_distance) ...
        || params.inner_distance < 0 ...
        || params.inner_distance ~= round(params.inner_distance)
    error('AAA:Algorithms:InvalidBackgroundInnerDistance', ...
        'profile.roi.background.inner_distance must be one nonnegative integer.');
end
if ~isnumeric(params.outer_distance) ...
        || ~isscalar(params.outer_distance) ...
        || ~isfinite(params.outer_distance) ...
        || params.outer_distance <= params.inner_distance ...
        || params.outer_distance ~= round(params.outer_distance)
    error('AAA:Algorithms:InvalidBackgroundOuterDistance', ...
        'profile.roi.background.outer_distance must exceed inner_distance.');
end
if ~isnumeric(params.background_fraction) ...
        || ~isscalar(params.background_fraction) ...
        || ~isfinite(params.background_fraction) ...
        || params.background_fraction <= 0 ...
        || params.background_fraction > 1
    error('AAA:Algorithms:InvalidBackgroundFraction', ...
        'profile.roi.background.background_fraction must be in (0, 1].');
end
if ~isnumeric(params.fit_span) || ~isscalar(params.fit_span) ...
        || ~isfinite(params.fit_span) || params.fit_span <= 0 ...
        || params.fit_span > 1
    error('AAA:Algorithms:InvalidBackgroundFitSpan', ...
        'profile.roi.background.fit_span must be in (0, 1].');
end
if ~(ischar(params.fit_method) && isrow(params.fit_method)) ...
        && ~(isstring(params.fit_method) && isscalar(params.fit_method))
    error('AAA:Algorithms:InvalidBackgroundFitMethod', ...
        'profile.roi.background.fit_method must be one text scalar.');
end
end

function roi_mask = validate_roi_mask(roi_mask, frame_size)
if (~isnumeric(roi_mask) && ~islogical(roi_mask)) || ~isreal(roi_mask) ...
        || ~ismatrix(roi_mask) || ~isequal(size(roi_mask), frame_size)
    error('AAA:Algorithms:InvalidRoiMask', ...
        'ROI mask must be one real [%d %d] label matrix.', ...
        frame_size(1), frame_size(2));
end
values = double(roi_mask(:));
if any(~isfinite(values)) || any(values < 0) ...
        || any(values ~= round(values))
    error('AAA:Algorithms:InvalidRoiMaskLabels', ...
        'ROI mask labels must be finite nonnegative integers.');
end
labels = unique(values(values > 0), 'sorted');
if ~isequal(labels(:)', 1:numel(labels))
    error('AAA:Algorithms:NoncontiguousRoiLabels', ...
        ['Background removal preserves the frozen 1:n ROI contract; ' ...
         'positive ROI labels must be contiguous.']);
end
end
