function results = store_trace_stage(results, stage_name, data, parent_results, roi_file, movie_info, method, parameters)
%STORE_TRACE_STAGE Store a trace stage with the frozen Dual provenance schema.
%
% parent_results is stored in the supplied order. This function does not
% infer, sort, or replace parents.

results.trace_results.(stage_name).data = data;
results.trace_results.(stage_name).info = struct( ...
    'result_name', stage_name, ...
    'parent_results', {parent_results}, ...
    'roi_file', roi_file, ...
    'movie_source', movie_info.source_path, ...
    'transpose_before_analysis', movie_info.transpose_before_analysis, ...
    'motion_applied', movie_info.motion.applied, ...
    'method', method, ...
    'parameters', parameters, ...
    'created_at', datetime("now"));
end
